package com.web.trabalho.Entidade;
// Generated 04/10/2018 16:22:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer cod;
     private Date data;
     private String total;
     private Integer idPessoa;
     private String qtd;
     private String codProd;

    public Pedido() {
    }

    public Pedido(Date data, String total, Integer idPessoa, String qtd, String codProd) {
       this.data = data;
       this.total = total;
       this.idPessoa = idPessoa;
       this.qtd = qtd;
       this.codProd = codProd;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public String getQtd() {
        return this.qtd;
    }
    
    public void setQtd(String qtd) {
        this.qtd = qtd;
    }
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }




}


