package com.web.trabalho.Entidade;
// Generated 04/10/2018 16:22:15 by Hibernate Tools 4.3.1



/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String cpf;
     private String rg;
     private String senha;

    public Pessoa() {
    }

    public Pessoa(String nome, String cpf, String rg, String senha) {
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.senha = senha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


